name: Trigger auto deployment for lazer-para-todos

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'backend/**'
    - '.github/workflows/lazer-para-todos-AutoDeployTrigger-7e5fe4f6-a5ce-41bd-a495-772b530f44a5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LAZERPARATODOS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/backend 
          registryUrl: lazerparatodosregistry.azurecr.io
          registryUsername: ${{ secrets.LAZERPARATODOS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LAZERPARATODOS_REGISTRY_PASSWORD }}
          containerAppName: lazer-para-todos
          resourceGroup: lazer-para-todos-rg
          imageToBuild: lazerparatodosregistry.azurecr.io/lazer-para-todos:${{ github.sha }}
          dockerfilePath: Dockerfile

     

